### ISSUE TITLE
Poppler binaries not installed

### ISSUE THREAD

**Issue by pankhuriagarwal94** [Belval/pdf2image-as-a-service#3]
Hi,
I am trying to install poppler binaries on aws lambda using your as-a-function amazon guide.
The directory poppler_binaries is being created but it is empty. Can you please tell how to resolve it?

**Comment by Belval** [comment]
Are you executing the script from the parent folder?

You should be doing `./amazon/lambda.sh` and not directly `./lambda.sh`.

**Comment by pankhuriagarwal94** [comment]
I am running it from parent folder only.
Probably this line - 
docker run -d --name poppler-build-cont test sleep 10
expects a test:latest image but u named it poppler-build

**Comment by Belval** [comment]
Nice catch! Thank you
