### ISSUE TITLE
 Lambda -> libjpeg.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by santiaghini** [Belval/pdf2image-as-a-service#6]
I'm trying  to make this work on AWS Lambda. I'm following the instructions in the README and running the scripts in an AWS instance with the same Amazon-Linux image used by Lambda.

Problem is, when testing the function I get the following error:

`pdf2image.exceptions.PDFPageCountError: Unable to get page count. poppler_binaries/pdfinfo: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`

What could be the cause? Am I doing something wrong?

**Comment by Belval** [comment]
Interesting, that would indicate that the libjpeg file was not in the uploaded package. Can you unzip it to make sure that it's there?

**Comment by santiaghini** [comment]
Changed to an Ubuntu instance to recompile.

Now I'm getting this error:
`Unable to get page count. poppler_binaries/pdfinfo: error while loading shared libraries: libopenjp2.so.7: cannot open shared object file: No such file or directory`

In fact, it is not in the uploaded package.

From the logs I see the following:
`cp: missing destination file operand after '/poppler_binaries/'`

Maybe from line 15 in `build_poppler.sh`?:
`cp $(ldconfig -p | grep libopenjp2.so.7 | head -n 1 | tr ' ' '\n' | grep /) /poppler_binaries/; \`

What is your recommendation?

**Comment by Belval** [comment]
It's quite weird, what version of Ubuntu are you using?

You can install libopenjp2.so.7 with `sudo apt install libopenjp2-7` and it should find it.

**Comment by Belval** [comment]
Actually from the `Dockerfile` it should already be installed. Are you building poppler using the provided `Dockerfile`?

**Comment by santiaghini** [comment]
Yes, I tried with the provided Dockerfile. In fact I followed your instructions in the README.

I think it may be because I'm missing some dependency.

Anyways, I tried with the approach provided by @kevin-hsieh in the pull request, and it finally worked!

**Comment by Belval** [comment]
Good to know, it will be merged soon so hopefully we can all skip building from scratch.

**Comment by Belval** [comment]
The PR was merged a while ago and AFAIK this is now resolved. Feel free to reopen if the issue persists.
